/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Object = System.Object;
using InvalidOperationException = System.InvalidOperationException;
using Exception = System.Exception;
using ArgumentNullException = System.ArgumentNullException;
using SystemEventHandler = System.EventHandler;
using DateTimeOffset = System.DateTimeOffset;
using Guid = System.Guid;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using IApiAccessor = Finbourne.Workflow.Sdk.Client.IApiAccessor;
using Finbourne.Workflow.Sdk.Extensions;
using Finbourne.Workflow.Sdk.Client.Auth;
using Finbourne.Workflow.Sdk.Model;

namespace Finbourne.Workflow.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILaunchersApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// [EXPERIMENTAL] CreateLauncher: Create a new Launcher on a Workflow
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="createLauncherRequest">The data to create a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>LauncherResponse</returns>
        LauncherResponse CreateLauncher(string scope, string code, CreateLauncherRequest createLauncherRequest, int operationIndex = 0, ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] CreateLauncher: Create a new Launcher on a Workflow
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="createLauncherRequest">The data to create a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of LauncherResponse</returns>
        Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse> CreateLauncherWithHttpInfo(string scope, string code, CreateLauncherRequest createLauncherRequest, int operationIndex = 0, ConfigurationOptions? opts = null);
        /// <summary>
        /// [EXPERIMENTAL] DeleteLauncher: Delete a Launcher of a Workflow
        /// </summary>
        /// <remarks>
        /// If the Launcher does not exist a failure will be returned
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>DeletedEntityResponse</returns>
        DeletedEntityResponse DeleteLauncher(string scope, string code, string launcherId, int operationIndex = 0, ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] DeleteLauncher: Delete a Launcher of a Workflow
        /// </summary>
        /// <remarks>
        /// If the Launcher does not exist a failure will be returned
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of DeletedEntityResponse</returns>
        Finbourne.Workflow.Sdk.Client.ApiResponse<DeletedEntityResponse> DeleteLauncherWithHttpInfo(string scope, string code, string launcherId, int operationIndex = 0, ConfigurationOptions? opts = null);
        /// <summary>
        /// [EXPERIMENTAL] UpdateLauncher: Update an existing Launcher of a Workflow
        /// </summary>
        /// <remarks>
        /// The type of a Launcher cannot be changed
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="updateLauncherRequest">The data to update a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>LauncherResponse</returns>
        LauncherResponse UpdateLauncher(string scope, string code, string launcherId, UpdateLauncherRequest updateLauncherRequest, int operationIndex = 0, ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] UpdateLauncher: Update an existing Launcher of a Workflow
        /// </summary>
        /// <remarks>
        /// The type of a Launcher cannot be changed
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="updateLauncherRequest">The data to update a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of LauncherResponse</returns>
        Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse> UpdateLauncherWithHttpInfo(string scope, string code, string launcherId, UpdateLauncherRequest updateLauncherRequest, int operationIndex = 0, ConfigurationOptions? opts = null);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILaunchersApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// [EXPERIMENTAL] CreateLauncher: Create a new Launcher on a Workflow
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="createLauncherRequest">The data to create a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of LauncherResponse</returns>
        System.Threading.Tasks.Task<LauncherResponse> CreateLauncherAsync(string scope, string code, CreateLauncherRequest createLauncherRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] CreateLauncher: Create a new Launcher on a Workflow
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="createLauncherRequest">The data to create a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (LauncherResponse)</returns>
        System.Threading.Tasks.Task<Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse>> CreateLauncherWithHttpInfoAsync(string scope, string code, CreateLauncherRequest createLauncherRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);
        /// <summary>
        /// [EXPERIMENTAL] DeleteLauncher: Delete a Launcher of a Workflow
        /// </summary>
        /// <remarks>
        /// If the Launcher does not exist a failure will be returned
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of DeletedEntityResponse</returns>
        System.Threading.Tasks.Task<DeletedEntityResponse> DeleteLauncherAsync(string scope, string code, string launcherId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] DeleteLauncher: Delete a Launcher of a Workflow
        /// </summary>
        /// <remarks>
        /// If the Launcher does not exist a failure will be returned
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (DeletedEntityResponse)</returns>
        System.Threading.Tasks.Task<Finbourne.Workflow.Sdk.Client.ApiResponse<DeletedEntityResponse>> DeleteLauncherWithHttpInfoAsync(string scope, string code, string launcherId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);
        /// <summary>
        /// [EXPERIMENTAL] UpdateLauncher: Update an existing Launcher of a Workflow
        /// </summary>
        /// <remarks>
        /// The type of a Launcher cannot be changed
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="updateLauncherRequest">The data to update a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of LauncherResponse</returns>
        System.Threading.Tasks.Task<LauncherResponse> UpdateLauncherAsync(string scope, string code, string launcherId, UpdateLauncherRequest updateLauncherRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] UpdateLauncher: Update an existing Launcher of a Workflow
        /// </summary>
        /// <remarks>
        /// The type of a Launcher cannot be changed
        /// </remarks>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="updateLauncherRequest">The data to update a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (LauncherResponse)</returns>
        System.Threading.Tasks.Task<Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse>> UpdateLauncherWithHttpInfoAsync(string scope, string code, string launcherId, UpdateLauncherRequest updateLauncherRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILaunchersApi : ILaunchersApiSync, ILaunchersApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LaunchersApi : ILaunchersApi
    {
        private Finbourne.Workflow.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LaunchersApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LaunchersApi(string basePath)
        {
            var globalConfiguration = Finbourne.Workflow.Sdk.Client.GlobalConfiguration.Instance;
            this.Configuration = Finbourne.Workflow.Sdk.Client.Configuration.MergeConfigurations(
                globalConfiguration,
                new Finbourne.Workflow.Sdk.Client.Configuration
                {
                    BasePath = basePath,
                    TimeoutMs = globalConfiguration.TimeoutMs,
                    RateLimitRetries = globalConfiguration.RateLimitRetries
                }
            );
            this.Client = new Finbourne.Workflow.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Finbourne.Workflow.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Finbourne.Workflow.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchersApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LaunchersApi(Finbourne.Workflow.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = configuration;
            this.Client = new Finbourne.Workflow.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Finbourne.Workflow.Sdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Finbourne.Workflow.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public LaunchersApi(Finbourne.Workflow.Sdk.Client.ISynchronousClient client, Finbourne.Workflow.Sdk.Client.IAsynchronousClient asyncClient, Finbourne.Workflow.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Finbourne.Workflow.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Finbourne.Workflow.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Finbourne.Workflow.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Finbourne.Workflow.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Finbourne.Workflow.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// [EXPERIMENTAL] CreateLauncher: Create a new Launcher on a Workflow 
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="createLauncherRequest">The data to create a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>LauncherResponse</returns>
        public LauncherResponse CreateLauncher(string scope, string code, CreateLauncherRequest createLauncherRequest, int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse> localVarResponse = CreateLauncherWithHttpInfo(scope, code, createLauncherRequest, opts: opts);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] CreateLauncher: Create a new Launcher on a Workflow 
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="createLauncherRequest">The data to create a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of LauncherResponse</returns>
        public Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse> CreateLauncherWithHttpInfo(string scope, string code, CreateLauncherRequest createLauncherRequest, int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'scope' when calling LaunchersApi->CreateLauncher");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'code' when calling LaunchersApi->CreateLauncher");
            }

            // verify the required parameter 'createLauncherRequest' is set
            if (createLauncherRequest == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'createLauncherRequest' when calling LaunchersApi->CreateLauncher");
            }

            Finbourne.Workflow.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Workflow.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = createLauncherRequest;

            localVarRequestOptions.Operation = "LaunchersApi.CreateLauncher";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<LauncherResponse>("/api/workflows/{scope}/{code}/launchers", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateLauncher", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EXPERIMENTAL] CreateLauncher: Create a new Launcher on a Workflow 
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="createLauncherRequest">The data to create a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of LauncherResponse</returns>
        public async System.Threading.Tasks.Task<LauncherResponse> CreateLauncherAsync(string scope, string code, CreateLauncherRequest createLauncherRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse> localVarResponse = await CreateLauncherWithHttpInfoAsync(scope, code, createLauncherRequest, operationIndex, cancellationToken, opts).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] CreateLauncher: Create a new Launcher on a Workflow 
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="createLauncherRequest">The data to create a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (LauncherResponse)</returns>
        public async System.Threading.Tasks.Task<Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse>> CreateLauncherWithHttpInfoAsync(string scope, string code, CreateLauncherRequest createLauncherRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'scope' when calling LaunchersApi->CreateLauncher");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'code' when calling LaunchersApi->CreateLauncher");
            }

            // verify the required parameter 'createLauncherRequest' is set
            if (createLauncherRequest == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'createLauncherRequest' when calling LaunchersApi->CreateLauncher");
            }


            Finbourne.Workflow.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Workflow.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.Data = createLauncherRequest;

            localVarRequestOptions.Operation = "LaunchersApi.CreateLauncher";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<LauncherResponse>("/api/workflows/{scope}/{code}/launchers", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateLauncher", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EXPERIMENTAL] DeleteLauncher: Delete a Launcher of a Workflow If the Launcher does not exist a failure will be returned
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>DeletedEntityResponse</returns>
        public DeletedEntityResponse DeleteLauncher(string scope, string code, string launcherId, int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            Finbourne.Workflow.Sdk.Client.ApiResponse<DeletedEntityResponse> localVarResponse = DeleteLauncherWithHttpInfo(scope, code, launcherId, opts: opts);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] DeleteLauncher: Delete a Launcher of a Workflow If the Launcher does not exist a failure will be returned
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of DeletedEntityResponse</returns>
        public Finbourne.Workflow.Sdk.Client.ApiResponse<DeletedEntityResponse> DeleteLauncherWithHttpInfo(string scope, string code, string launcherId, int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'scope' when calling LaunchersApi->DeleteLauncher");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'code' when calling LaunchersApi->DeleteLauncher");
            }

            // verify the required parameter 'launcherId' is set
            if (launcherId == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'launcherId' when calling LaunchersApi->DeleteLauncher");
            }

            Finbourne.Workflow.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Workflow.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("launcherId", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(launcherId)); // path parameter

            localVarRequestOptions.Operation = "LaunchersApi.DeleteLauncher";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<DeletedEntityResponse>("/api/workflows/{scope}/{code}/launchers/{launcherId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteLauncher", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EXPERIMENTAL] DeleteLauncher: Delete a Launcher of a Workflow If the Launcher does not exist a failure will be returned
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of DeletedEntityResponse</returns>
        public async System.Threading.Tasks.Task<DeletedEntityResponse> DeleteLauncherAsync(string scope, string code, string launcherId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            Finbourne.Workflow.Sdk.Client.ApiResponse<DeletedEntityResponse> localVarResponse = await DeleteLauncherWithHttpInfoAsync(scope, code, launcherId, operationIndex, cancellationToken, opts).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] DeleteLauncher: Delete a Launcher of a Workflow If the Launcher does not exist a failure will be returned
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (DeletedEntityResponse)</returns>
        public async System.Threading.Tasks.Task<Finbourne.Workflow.Sdk.Client.ApiResponse<DeletedEntityResponse>> DeleteLauncherWithHttpInfoAsync(string scope, string code, string launcherId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'scope' when calling LaunchersApi->DeleteLauncher");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'code' when calling LaunchersApi->DeleteLauncher");
            }

            // verify the required parameter 'launcherId' is set
            if (launcherId == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'launcherId' when calling LaunchersApi->DeleteLauncher");
            }


            Finbourne.Workflow.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Workflow.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("launcherId", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(launcherId)); // path parameter

            localVarRequestOptions.Operation = "LaunchersApi.DeleteLauncher";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<DeletedEntityResponse>("/api/workflows/{scope}/{code}/launchers/{launcherId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteLauncher", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EXPERIMENTAL] UpdateLauncher: Update an existing Launcher of a Workflow The type of a Launcher cannot be changed
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="updateLauncherRequest">The data to update a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>LauncherResponse</returns>
        public LauncherResponse UpdateLauncher(string scope, string code, string launcherId, UpdateLauncherRequest updateLauncherRequest, int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse> localVarResponse = UpdateLauncherWithHttpInfo(scope, code, launcherId, updateLauncherRequest, opts: opts);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] UpdateLauncher: Update an existing Launcher of a Workflow The type of a Launcher cannot be changed
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="updateLauncherRequest">The data to update a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of LauncherResponse</returns>
        public Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse> UpdateLauncherWithHttpInfo(string scope, string code, string launcherId, UpdateLauncherRequest updateLauncherRequest, int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'scope' when calling LaunchersApi->UpdateLauncher");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'code' when calling LaunchersApi->UpdateLauncher");
            }

            // verify the required parameter 'launcherId' is set
            if (launcherId == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'launcherId' when calling LaunchersApi->UpdateLauncher");
            }

            // verify the required parameter 'updateLauncherRequest' is set
            if (updateLauncherRequest == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'updateLauncherRequest' when calling LaunchersApi->UpdateLauncher");
            }

            Finbourne.Workflow.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Workflow.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("launcherId", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(launcherId)); // path parameter
            localVarRequestOptions.Data = updateLauncherRequest;

            localVarRequestOptions.Operation = "LaunchersApi.UpdateLauncher";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<LauncherResponse>("/api/workflows/{scope}/{code}/launchers/{launcherId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateLauncher", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EXPERIMENTAL] UpdateLauncher: Update an existing Launcher of a Workflow The type of a Launcher cannot be changed
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="updateLauncherRequest">The data to update a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of LauncherResponse</returns>
        public async System.Threading.Tasks.Task<LauncherResponse> UpdateLauncherAsync(string scope, string code, string launcherId, UpdateLauncherRequest updateLauncherRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse> localVarResponse = await UpdateLauncherWithHttpInfoAsync(scope, code, launcherId, updateLauncherRequest, operationIndex, cancellationToken, opts).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] UpdateLauncher: Update an existing Launcher of a Workflow The type of a Launcher cannot be changed
        /// </summary>
        /// <exception cref="Finbourne.Workflow.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope that identifies the Workflow that owns the Launcher</param>
        /// <param name="code">The code that identifies the Workflow that owns the Launcher</param>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow</param>
        /// <param name="updateLauncherRequest">The data to update a Launcher</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (LauncherResponse)</returns>
        public async System.Threading.Tasks.Task<Finbourne.Workflow.Sdk.Client.ApiResponse<LauncherResponse>> UpdateLauncherWithHttpInfoAsync(string scope, string code, string launcherId, UpdateLauncherRequest updateLauncherRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'scope' when calling LaunchersApi->UpdateLauncher");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'code' when calling LaunchersApi->UpdateLauncher");
            }

            // verify the required parameter 'launcherId' is set
            if (launcherId == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'launcherId' when calling LaunchersApi->UpdateLauncher");
            }

            // verify the required parameter 'updateLauncherRequest' is set
            if (updateLauncherRequest == null)
            {
                throw new Finbourne.Workflow.Sdk.Client.ApiException(400, "Missing required parameter 'updateLauncherRequest' when calling LaunchersApi->UpdateLauncher");
            }


            Finbourne.Workflow.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Workflow.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Workflow.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.PathParameters.Add("launcherId", Finbourne.Workflow.Sdk.Client.ClientUtils.ParameterToString(launcherId)); // path parameter
            localVarRequestOptions.Data = updateLauncherRequest;

            localVarRequestOptions.Operation = "LaunchersApi.UpdateLauncher";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<LauncherResponse>("/api/workflows/{scope}/{code}/launchers/{launcherId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateLauncher", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}