/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Defines the Actions for a Task
    /// </summary>
    [DataContract(Name = "ActionDefinition")]
    public partial class ActionDefinition : IEquatable<ActionDefinition>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionDefinition" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ActionDefinition() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionDefinition" /> class.
        /// </summary>
        /// <param name="name">The Name of this Action (required).</param>
        /// <param name="runAsUserId">The ID of the user that this action will be performed by. If not specified, the actions will be performed by the \&quot;current user\&quot;..</param>
        /// <param name="actionDetails">actionDetails (required).</param>
        /// <param name="displayName">The display name of this Action.</param>
        /// <param name="description">The description of this Action.</param>
        public ActionDefinition(string name = default(string), string runAsUserId = default(string), ActionDetails actionDetails = default(ActionDetails), string displayName = default(string), string description = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ActionDefinition and cannot be null");
            }
            this.Name = name;
            // to ensure "actionDetails" is required (not null)
            if (actionDetails == null)
            {
                throw new ArgumentNullException("actionDetails is a required property for ActionDefinition and cannot be null");
            }
            this.ActionDetails = actionDetails;
            this.RunAsUserId = runAsUserId;
            this.DisplayName = displayName;
            this.Description = description;
        }

        /// <summary>
        /// The Name of this Action
        /// </summary>
        /// <value>The Name of this Action</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The ID of the user that this action will be performed by. If not specified, the actions will be performed by the \&quot;current user\&quot;.
        /// </summary>
        /// <value>The ID of the user that this action will be performed by. If not specified, the actions will be performed by the \&quot;current user\&quot;.</value>
        [DataMember(Name = "runAsUserId", EmitDefaultValue = true)]
        public string RunAsUserId { get; set; }

        /// <summary>
        /// Gets or Sets ActionDetails
        /// </summary>
        [DataMember(Name = "actionDetails", IsRequired = true, EmitDefaultValue = true)]
        public ActionDetails ActionDetails { get; set; }

        /// <summary>
        /// The display name of this Action
        /// </summary>
        /// <value>The display name of this Action</value>
        [DataMember(Name = "displayName", EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// The description of this Action
        /// </summary>
        /// <value>The description of this Action</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActionDefinition {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RunAsUserId: ").Append(RunAsUserId).Append("\n");
            sb.Append("  ActionDetails: ").Append(ActionDetails).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ActionDefinition);
        }

        /// <summary>
        /// Returns true if ActionDefinition instances are equal
        /// </summary>
        /// <param name="input">Instance of ActionDefinition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ActionDefinition input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.RunAsUserId == input.RunAsUserId ||
                    (this.RunAsUserId != null &&
                    this.RunAsUserId.Equals(input.RunAsUserId))
                ) && 
                (
                    this.ActionDetails == input.ActionDetails ||
                    (this.ActionDetails != null &&
                    this.ActionDetails.Equals(input.ActionDetails))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.RunAsUserId != null)
                {
                    hashCode = (hashCode * 59) + this.RunAsUserId.GetHashCode();
                }
                if (this.ActionDetails != null)
                {
                    hashCode = (hashCode * 59) + this.ActionDetails.GetHashCode();
                }
                if (this.DisplayName != null)
                {
                    hashCode = (hashCode * 59) + this.DisplayName.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be less than 1024.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Name (string) pattern
            Regex regexName = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexName.Match(this.Name).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, must match a pattern of " + regexName, new [] { "Name" });
            }

            // RunAsUserId (string) maxLength
            if (this.RunAsUserId != null && this.RunAsUserId.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RunAsUserId, length must be less than 1024.", new [] { "RunAsUserId" });
            }

            // RunAsUserId (string) pattern
            Regex regexRunAsUserId = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexRunAsUserId.Match(this.RunAsUserId).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RunAsUserId, must match a pattern of " + regexRunAsUserId, new [] { "RunAsUserId" });
            }

            // DisplayName (string) maxLength
            if (this.DisplayName != null && this.DisplayName.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DisplayName, length must be less than 1024.", new [] { "DisplayName" });
            }

            // DisplayName (string) minLength
            if (this.DisplayName != null && this.DisplayName.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DisplayName, length must be greater than 1.", new [] { "DisplayName" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, length must be less than 1024.", new [] { "Description" });
            }

            // Description (string) minLength
            if (this.Description != null && this.Description.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, length must be greater than 0.", new [] { "Description" });
            }

            // Description (string) pattern
            Regex regexDescription = new Regex(@"^[\s\S]*$", RegexOptions.CultureInvariant);
            if (false == regexDescription.Match(this.Description).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Description, must match a pattern of " + regexDescription, new [] { "Description" });
            }

            yield break;
        }
    }
}
