/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// A named time zone and set of holiday calendars.
    /// </summary>
    [DataContract(Name = "CalendarContext")]
    public partial class CalendarContext : IEquatable<CalendarContext>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CalendarContext" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CalendarContext() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CalendarContext" /> class.
        /// </summary>
        /// <param name="name">The name the schedule and the date and time adjustments use to name this context (required).</param>
        /// <param name="varTimeZone">The time zone to use. A TZ identifier, for example \&quot;Europe/London\&quot; (required).</param>
        /// <param name="holidayCalendars">The holiday calendars that decide which dates are business days in this context.</param>
        public CalendarContext(string name = default(string), string varTimeZone = default(string), List<CalendarReference> holidayCalendars = default(List<CalendarReference>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CalendarContext and cannot be null");
            }
            this.Name = name;
            // to ensure "varTimeZone" is required (not null)
            if (varTimeZone == null)
            {
                throw new ArgumentNullException("varTimeZone is a required property for CalendarContext and cannot be null");
            }
            this.VarTimeZone = varTimeZone;
            this.HolidayCalendars = holidayCalendars;
        }

        /// <summary>
        /// The name the schedule and the date and time adjustments use to name this context
        /// </summary>
        /// <value>The name the schedule and the date and time adjustments use to name this context</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The time zone to use. A TZ identifier, for example \&quot;Europe/London\&quot;
        /// </summary>
        /// <value>The time zone to use. A TZ identifier, for example \&quot;Europe/London\&quot;</value>
        [DataMember(Name = "timeZone", IsRequired = true, EmitDefaultValue = true)]
        public string VarTimeZone { get; set; }

        /// <summary>
        /// The holiday calendars that decide which dates are business days in this context
        /// </summary>
        /// <value>The holiday calendars that decide which dates are business days in this context</value>
        [DataMember(Name = "holidayCalendars", EmitDefaultValue = true)]
        public List<CalendarReference> HolidayCalendars { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CalendarContext {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  VarTimeZone: ").Append(VarTimeZone).Append("\n");
            sb.Append("  HolidayCalendars: ").Append(HolidayCalendars).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CalendarContext);
        }

        /// <summary>
        /// Returns true if CalendarContext instances are equal
        /// </summary>
        /// <param name="input">Instance of CalendarContext to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CalendarContext input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.VarTimeZone == input.VarTimeZone ||
                    (this.VarTimeZone != null &&
                    this.VarTimeZone.Equals(input.VarTimeZone))
                ) && 
                (
                    this.HolidayCalendars == input.HolidayCalendars ||
                    this.HolidayCalendars != null &&
                    input.HolidayCalendars != null &&
                    this.HolidayCalendars.SequenceEqual(input.HolidayCalendars)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.VarTimeZone != null)
                {
                    hashCode = (hashCode * 59) + this.VarTimeZone.GetHashCode();
                }
                if (this.HolidayCalendars != null)
                {
                    hashCode = (hashCode * 59) + this.HolidayCalendars.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be less than 64.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Name (string) pattern
            Regex regexName = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexName.Match(this.Name).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, must match a pattern of " + regexName, new [] { "Name" });
            }

            // VarTimeZone (string) maxLength
            if (this.VarTimeZone != null && this.VarTimeZone.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for VarTimeZone, length must be less than 100.", new [] { "VarTimeZone" });
            }

            // VarTimeZone (string) minLength
            if (this.VarTimeZone != null && this.VarTimeZone.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for VarTimeZone, length must be greater than 1.", new [] { "VarTimeZone" });
            }

            yield break;
        }
    }
}
