/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Represents a parent-child relationship between two Task Definitions in a Workflow
    /// </summary>
    [DataContract(Name = "ChildTaskDefinitionEdge")]
    public partial class ChildTaskDefinitionEdge : IEquatable<ChildTaskDefinitionEdge>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChildTaskDefinitionEdge" /> class.
        /// </summary>
        /// <param name="parent">parent.</param>
        /// <param name="child">child.</param>
        public ChildTaskDefinitionEdge(VersionedTaskDefinitionId parent = default(VersionedTaskDefinitionId), VersionedTaskDefinitionId child = default(VersionedTaskDefinitionId))
        {
            this.Parent = parent;
            this.Child = child;
        }

        /// <summary>
        /// Gets or Sets Parent
        /// </summary>
        [DataMember(Name = "parent", EmitDefaultValue = false)]
        public VersionedTaskDefinitionId Parent { get; set; }

        /// <summary>
        /// Gets or Sets Child
        /// </summary>
        [DataMember(Name = "child", EmitDefaultValue = false)]
        public VersionedTaskDefinitionId Child { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChildTaskDefinitionEdge {\n");
            sb.Append("  Parent: ").Append(Parent).Append("\n");
            sb.Append("  Child: ").Append(Child).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChildTaskDefinitionEdge);
        }

        /// <summary>
        /// Returns true if ChildTaskDefinitionEdge instances are equal
        /// </summary>
        /// <param name="input">Instance of ChildTaskDefinitionEdge to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChildTaskDefinitionEdge input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Parent == input.Parent ||
                    (this.Parent != null &&
                    this.Parent.Equals(input.Parent))
                ) && 
                (
                    this.Child == input.Child ||
                    (this.Child != null &&
                    this.Child.Equals(input.Child))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Parent != null)
                {
                    hashCode = (hashCode * 59) + this.Parent.GetHashCode();
                }
                if (this.Child != null)
                {
                    hashCode = (hashCode * 59) + this.Child.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
