/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// A change applied to the date and the time of a source value, in a named calendar context.              At least one of Finbourne.Workflow.WebApi.Common.Dto.Json.Launchers.DateTimeAdjustment.DateAdjustment or Finbourne.Workflow.WebApi.Common.Dto.Json.Launchers.DateTimeAdjustment.TimeAdjustment must be given
    /// </summary>
    [DataContract(Name = "DateTimeAdjustment")]
    public partial class DateTimeAdjustment : IEquatable<DateTimeAdjustment>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DateTimeAdjustment" /> class.
        /// </summary>
        /// <param name="calendarContext">The name of the calendar context this change happens in, which must be one the Launcher declares. When it is left out a Schedule Launcher uses the context of its schedule.</param>
        /// <param name="dateAdjustment">dateAdjustment.</param>
        /// <param name="timeAdjustment">timeAdjustment.</param>
        public DateTimeAdjustment(string calendarContext = default(string), DateAdjustment dateAdjustment = default(DateAdjustment), TimeAdjustment timeAdjustment = default(TimeAdjustment))
        {
            this.CalendarContext = calendarContext;
            this.DateAdjustment = dateAdjustment;
            this.TimeAdjustment = timeAdjustment;
        }

        /// <summary>
        /// The name of the calendar context this change happens in, which must be one the Launcher declares. When it is left out a Schedule Launcher uses the context of its schedule
        /// </summary>
        /// <value>The name of the calendar context this change happens in, which must be one the Launcher declares. When it is left out a Schedule Launcher uses the context of its schedule</value>
        [DataMember(Name = "calendarContext", EmitDefaultValue = true)]
        public string CalendarContext { get; set; }

        /// <summary>
        /// Gets or Sets DateAdjustment
        /// </summary>
        [DataMember(Name = "dateAdjustment", EmitDefaultValue = false)]
        public DateAdjustment DateAdjustment { get; set; }

        /// <summary>
        /// Gets or Sets TimeAdjustment
        /// </summary>
        [DataMember(Name = "timeAdjustment", EmitDefaultValue = false)]
        public TimeAdjustment TimeAdjustment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DateTimeAdjustment {\n");
            sb.Append("  CalendarContext: ").Append(CalendarContext).Append("\n");
            sb.Append("  DateAdjustment: ").Append(DateAdjustment).Append("\n");
            sb.Append("  TimeAdjustment: ").Append(TimeAdjustment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DateTimeAdjustment);
        }

        /// <summary>
        /// Returns true if DateTimeAdjustment instances are equal
        /// </summary>
        /// <param name="input">Instance of DateTimeAdjustment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DateTimeAdjustment input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CalendarContext == input.CalendarContext ||
                    (this.CalendarContext != null &&
                    this.CalendarContext.Equals(input.CalendarContext))
                ) && 
                (
                    this.DateAdjustment == input.DateAdjustment ||
                    (this.DateAdjustment != null &&
                    this.DateAdjustment.Equals(input.DateAdjustment))
                ) && 
                (
                    this.TimeAdjustment == input.TimeAdjustment ||
                    (this.TimeAdjustment != null &&
                    this.TimeAdjustment.Equals(input.TimeAdjustment))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CalendarContext != null)
                {
                    hashCode = (hashCode * 59) + this.CalendarContext.GetHashCode();
                }
                if (this.DateAdjustment != null)
                {
                    hashCode = (hashCode * 59) + this.DateAdjustment.GetHashCode();
                }
                if (this.TimeAdjustment != null)
                {
                    hashCode = (hashCode * 59) + this.TimeAdjustment.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CalendarContext (string) maxLength
            if (this.CalendarContext != null && this.CalendarContext.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CalendarContext, length must be less than 64.", new [] { "CalendarContext" });
            }

            // CalendarContext (string) minLength
            if (this.CalendarContext != null && this.CalendarContext.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CalendarContext, length must be greater than 1.", new [] { "CalendarContext" });
            }

            // CalendarContext (string) pattern
            Regex regexCalendarContext = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexCalendarContext.Match(this.CalendarContext).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CalendarContext, must match a pattern of " + regexCalendarContext, new [] { "CalendarContext" });
            }

            yield break;
        }
    }
}
