/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// A Launcher that starts a run of its Workflow when a matching platform event arrives, and can fill fields and correlation IDs of the root task from that event
    /// </summary>
    [DataContract(Name = "EventLauncherDetails")]
    public partial class EventLauncherDetails : IEquatable<EventLauncherDetails>, IValidatableObject
    {
        /// <summary>
        /// Defines LauncherType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LauncherTypeEnum
        {
            /// <summary>
            /// Enum Event for value: Event
            /// </summary>
            [EnumMember(Value = "Event")]
            Event = 1
        }


        /// <summary>
        /// Gets or Sets LauncherType
        /// </summary>
        [DataMember(Name = "launcherType", IsRequired = true, EmitDefaultValue = true)]
        public LauncherTypeEnum LauncherType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventLauncherDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventLauncherDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventLauncherDetails" /> class.
        /// </summary>
        /// <param name="launcherType">launcherType (required).</param>
        /// <param name="eventMatchingPattern">eventMatchingPattern (required).</param>
        /// <param name="mapTaskFields">Fields of the root task filled from the event, keyed by the field name on the root task definition.</param>
        /// <param name="mapCorrelationIds">Correlation IDs of the root task filled from the event.</param>
        /// <param name="runAsUserId">runAsUserId (required).</param>
        /// <param name="setTaskFields">Fields of the root task set to a fixed value, keyed by the field name on the root task definition.</param>
        /// <param name="setCorrelationIds">Correlation IDs put on the root task as given.</param>
        /// <param name="initialTrigger">The trigger given to the root task once it is made and all of its fields are filled. When it is left out the root task is left in its initial state.</param>
        public EventLauncherDetails(LauncherTypeEnum launcherType = default(LauncherTypeEnum), LauncherEventMatchingPattern eventMatchingPattern = default(LauncherEventMatchingPattern), Dictionary<string, EventTaskFieldMapping> mapTaskFields = default(Dictionary<string, EventTaskFieldMapping>), List<CorrelationIdMapping> mapCorrelationIds = default(List<CorrelationIdMapping>), LauncherMapping runAsUserId = default(LauncherMapping), Dictionary<string, Object> setTaskFields = default(Dictionary<string, Object>), List<string> setCorrelationIds = default(List<string>), string initialTrigger = default(string))
        {
            this.LauncherType = launcherType;
            // to ensure "eventMatchingPattern" is required (not null)
            if (eventMatchingPattern == null)
            {
                throw new ArgumentNullException("eventMatchingPattern is a required property for EventLauncherDetails and cannot be null");
            }
            this.EventMatchingPattern = eventMatchingPattern;
            // to ensure "runAsUserId" is required (not null)
            if (runAsUserId == null)
            {
                throw new ArgumentNullException("runAsUserId is a required property for EventLauncherDetails and cannot be null");
            }
            this.RunAsUserId = runAsUserId;
            this.MapTaskFields = mapTaskFields;
            this.MapCorrelationIds = mapCorrelationIds;
            this.SetTaskFields = setTaskFields;
            this.SetCorrelationIds = setCorrelationIds;
            this.InitialTrigger = initialTrigger;
        }

        /// <summary>
        /// Gets or Sets EventMatchingPattern
        /// </summary>
        [DataMember(Name = "eventMatchingPattern", IsRequired = true, EmitDefaultValue = true)]
        public LauncherEventMatchingPattern EventMatchingPattern { get; set; }

        /// <summary>
        /// Fields of the root task filled from the event, keyed by the field name on the root task definition
        /// </summary>
        /// <value>Fields of the root task filled from the event, keyed by the field name on the root task definition</value>
        [DataMember(Name = "mapTaskFields", EmitDefaultValue = true)]
        public Dictionary<string, EventTaskFieldMapping> MapTaskFields { get; set; }

        /// <summary>
        /// Correlation IDs of the root task filled from the event
        /// </summary>
        /// <value>Correlation IDs of the root task filled from the event</value>
        [DataMember(Name = "mapCorrelationIds", EmitDefaultValue = true)]
        public List<CorrelationIdMapping> MapCorrelationIds { get; set; }

        /// <summary>
        /// Gets or Sets RunAsUserId
        /// </summary>
        [DataMember(Name = "runAsUserId", IsRequired = true, EmitDefaultValue = true)]
        public LauncherMapping RunAsUserId { get; set; }

        /// <summary>
        /// Fields of the root task set to a fixed value, keyed by the field name on the root task definition
        /// </summary>
        /// <value>Fields of the root task set to a fixed value, keyed by the field name on the root task definition</value>
        [DataMember(Name = "setTaskFields", EmitDefaultValue = true)]
        public Dictionary<string, Object> SetTaskFields { get; set; }

        /// <summary>
        /// Correlation IDs put on the root task as given
        /// </summary>
        /// <value>Correlation IDs put on the root task as given</value>
        [DataMember(Name = "setCorrelationIds", EmitDefaultValue = true)]
        public List<string> SetCorrelationIds { get; set; }

        /// <summary>
        /// The trigger given to the root task once it is made and all of its fields are filled. When it is left out the root task is left in its initial state
        /// </summary>
        /// <value>The trigger given to the root task once it is made and all of its fields are filled. When it is left out the root task is left in its initial state</value>
        [DataMember(Name = "initialTrigger", EmitDefaultValue = true)]
        public string InitialTrigger { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventLauncherDetails {\n");
            sb.Append("  LauncherType: ").Append(LauncherType).Append("\n");
            sb.Append("  EventMatchingPattern: ").Append(EventMatchingPattern).Append("\n");
            sb.Append("  MapTaskFields: ").Append(MapTaskFields).Append("\n");
            sb.Append("  MapCorrelationIds: ").Append(MapCorrelationIds).Append("\n");
            sb.Append("  RunAsUserId: ").Append(RunAsUserId).Append("\n");
            sb.Append("  SetTaskFields: ").Append(SetTaskFields).Append("\n");
            sb.Append("  SetCorrelationIds: ").Append(SetCorrelationIds).Append("\n");
            sb.Append("  InitialTrigger: ").Append(InitialTrigger).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EventLauncherDetails);
        }

        /// <summary>
        /// Returns true if EventLauncherDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of EventLauncherDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventLauncherDetails input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.LauncherType == input.LauncherType ||
                    this.LauncherType.Equals(input.LauncherType)
                ) && 
                (
                    this.EventMatchingPattern == input.EventMatchingPattern ||
                    (this.EventMatchingPattern != null &&
                    this.EventMatchingPattern.Equals(input.EventMatchingPattern))
                ) && 
                (
                    this.MapTaskFields == input.MapTaskFields ||
                    this.MapTaskFields != null &&
                    input.MapTaskFields != null &&
                    this.MapTaskFields.SequenceEqual(input.MapTaskFields)
                ) && 
                (
                    this.MapCorrelationIds == input.MapCorrelationIds ||
                    this.MapCorrelationIds != null &&
                    input.MapCorrelationIds != null &&
                    this.MapCorrelationIds.SequenceEqual(input.MapCorrelationIds)
                ) && 
                (
                    this.RunAsUserId == input.RunAsUserId ||
                    (this.RunAsUserId != null &&
                    this.RunAsUserId.Equals(input.RunAsUserId))
                ) && 
                (
                    this.SetTaskFields == input.SetTaskFields ||
                    this.SetTaskFields != null &&
                    input.SetTaskFields != null &&
                    this.SetTaskFields.SequenceEqual(input.SetTaskFields)
                ) && 
                (
                    this.SetCorrelationIds == input.SetCorrelationIds ||
                    this.SetCorrelationIds != null &&
                    input.SetCorrelationIds != null &&
                    this.SetCorrelationIds.SequenceEqual(input.SetCorrelationIds)
                ) && 
                (
                    this.InitialTrigger == input.InitialTrigger ||
                    (this.InitialTrigger != null &&
                    this.InitialTrigger.Equals(input.InitialTrigger))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.LauncherType.GetHashCode();
                if (this.EventMatchingPattern != null)
                {
                    hashCode = (hashCode * 59) + this.EventMatchingPattern.GetHashCode();
                }
                if (this.MapTaskFields != null)
                {
                    hashCode = (hashCode * 59) + this.MapTaskFields.GetHashCode();
                }
                if (this.MapCorrelationIds != null)
                {
                    hashCode = (hashCode * 59) + this.MapCorrelationIds.GetHashCode();
                }
                if (this.RunAsUserId != null)
                {
                    hashCode = (hashCode * 59) + this.RunAsUserId.GetHashCode();
                }
                if (this.SetTaskFields != null)
                {
                    hashCode = (hashCode * 59) + this.SetTaskFields.GetHashCode();
                }
                if (this.SetCorrelationIds != null)
                {
                    hashCode = (hashCode * 59) + this.SetCorrelationIds.GetHashCode();
                }
                if (this.InitialTrigger != null)
                {
                    hashCode = (hashCode * 59) + this.InitialTrigger.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // InitialTrigger (string) maxLength
            if (this.InitialTrigger != null && this.InitialTrigger.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for InitialTrigger, length must be less than 1024.", new [] { "InitialTrigger" });
            }

            // InitialTrigger (string) minLength
            if (this.InitialTrigger != null && this.InitialTrigger.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for InitialTrigger, length must be greater than 0.", new [] { "InitialTrigger" });
            }

            yield break;
        }
    }
}
