/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// How an Event Launcher fills one field of the root task from the event that arrived
    /// </summary>
    [DataContract(Name = "EventTaskFieldMapping")]
    public partial class EventTaskFieldMapping : IEquatable<EventTaskFieldMapping>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventTaskFieldMapping" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventTaskFieldMapping() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventTaskFieldMapping" /> class.
        /// </summary>
        /// <param name="mapFrom">The path into the event the value is taken from, for example header.timestamp (required).</param>
        /// <param name="dateTimeAdjustment">dateTimeAdjustment.</param>
        public EventTaskFieldMapping(string mapFrom = default(string), DateTimeAdjustment dateTimeAdjustment = default(DateTimeAdjustment))
        {
            // to ensure "mapFrom" is required (not null)
            if (mapFrom == null)
            {
                throw new ArgumentNullException("mapFrom is a required property for EventTaskFieldMapping and cannot be null");
            }
            this.MapFrom = mapFrom;
            this.DateTimeAdjustment = dateTimeAdjustment;
        }

        /// <summary>
        /// The path into the event the value is taken from, for example header.timestamp
        /// </summary>
        /// <value>The path into the event the value is taken from, for example header.timestamp</value>
        [DataMember(Name = "mapFrom", IsRequired = true, EmitDefaultValue = true)]
        public string MapFrom { get; set; }

        /// <summary>
        /// Gets or Sets DateTimeAdjustment
        /// </summary>
        [DataMember(Name = "dateTimeAdjustment", EmitDefaultValue = false)]
        public DateTimeAdjustment DateTimeAdjustment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventTaskFieldMapping {\n");
            sb.Append("  MapFrom: ").Append(MapFrom).Append("\n");
            sb.Append("  DateTimeAdjustment: ").Append(DateTimeAdjustment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EventTaskFieldMapping);
        }

        /// <summary>
        /// Returns true if EventTaskFieldMapping instances are equal
        /// </summary>
        /// <param name="input">Instance of EventTaskFieldMapping to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EventTaskFieldMapping input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MapFrom == input.MapFrom ||
                    (this.MapFrom != null &&
                    this.MapFrom.Equals(input.MapFrom))
                ) && 
                (
                    this.DateTimeAdjustment == input.DateTimeAdjustment ||
                    (this.DateTimeAdjustment != null &&
                    this.DateTimeAdjustment.Equals(input.DateTimeAdjustment))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MapFrom != null)
                {
                    hashCode = (hashCode * 59) + this.MapFrom.GetHashCode();
                }
                if (this.DateTimeAdjustment != null)
                {
                    hashCode = (hashCode * 59) + this.DateTimeAdjustment.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MapFrom (string) maxLength
            if (this.MapFrom != null && this.MapFrom.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MapFrom, length must be less than 1024.", new [] { "MapFrom" });
            }

            // MapFrom (string) minLength
            if (this.MapFrom != null && this.MapFrom.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MapFrom, length must be greater than 1.", new [] { "MapFrom" });
            }

            yield break;
        }
    }
}
