/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Behaviour applied to an existing (non-terminal) child task whose stacking key matches one or more new child task candidates
    /// </summary>
    [DataContract(Name = "ExistingTasksRecurringConfiguration")]
    public partial class ExistingTasksRecurringConfiguration : IEquatable<ExistingTasksRecurringConfiguration>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExistingTasksRecurringConfiguration" /> class.
        /// </summary>
        /// <param name="incrementAsAtModified">When true, the existing task&#39;s asAtModified is incremented even if no other change (Trigger or MergeFields) is applied.</param>
        /// <param name="trigger">The existing task receives this trigger.</param>
        /// <param name="mergeFields">The named fields on the existing task are updated with the values from the latest run. Only applies where the new-to-existing stacking key cardinality is one-to-one or one-to-many; unspecified fields are untouched. Data will be merged in even if these fields are in a read-only state..</param>
        public ExistingTasksRecurringConfiguration(bool incrementAsAtModified = default(bool), string trigger = default(string), List<string> mergeFields = default(List<string>))
        {
            this.IncrementAsAtModified = incrementAsAtModified;
            this.Trigger = trigger;
            this.MergeFields = mergeFields;
        }

        /// <summary>
        /// When true, the existing task&#39;s asAtModified is incremented even if no other change (Trigger or MergeFields) is applied
        /// </summary>
        /// <value>When true, the existing task&#39;s asAtModified is incremented even if no other change (Trigger or MergeFields) is applied</value>
        [DataMember(Name = "incrementAsAtModified", EmitDefaultValue = true)]
        public bool IncrementAsAtModified { get; set; }

        /// <summary>
        /// The existing task receives this trigger
        /// </summary>
        /// <value>The existing task receives this trigger</value>
        [DataMember(Name = "trigger", EmitDefaultValue = true)]
        public string Trigger { get; set; }

        /// <summary>
        /// The named fields on the existing task are updated with the values from the latest run. Only applies where the new-to-existing stacking key cardinality is one-to-one or one-to-many; unspecified fields are untouched. Data will be merged in even if these fields are in a read-only state.
        /// </summary>
        /// <value>The named fields on the existing task are updated with the values from the latest run. Only applies where the new-to-existing stacking key cardinality is one-to-one or one-to-many; unspecified fields are untouched. Data will be merged in even if these fields are in a read-only state.</value>
        [DataMember(Name = "mergeFields", EmitDefaultValue = true)]
        public List<string> MergeFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExistingTasksRecurringConfiguration {\n");
            sb.Append("  IncrementAsAtModified: ").Append(IncrementAsAtModified).Append("\n");
            sb.Append("  Trigger: ").Append(Trigger).Append("\n");
            sb.Append("  MergeFields: ").Append(MergeFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExistingTasksRecurringConfiguration);
        }

        /// <summary>
        /// Returns true if ExistingTasksRecurringConfiguration instances are equal
        /// </summary>
        /// <param name="input">Instance of ExistingTasksRecurringConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExistingTasksRecurringConfiguration input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.IncrementAsAtModified == input.IncrementAsAtModified ||
                    this.IncrementAsAtModified.Equals(input.IncrementAsAtModified)
                ) && 
                (
                    this.Trigger == input.Trigger ||
                    (this.Trigger != null &&
                    this.Trigger.Equals(input.Trigger))
                ) && 
                (
                    this.MergeFields == input.MergeFields ||
                    this.MergeFields != null &&
                    input.MergeFields != null &&
                    this.MergeFields.SequenceEqual(input.MergeFields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.IncrementAsAtModified.GetHashCode();
                if (this.Trigger != null)
                {
                    hashCode = (hashCode * 59) + this.Trigger.GetHashCode();
                }
                if (this.MergeFields != null)
                {
                    hashCode = (hashCode * 59) + this.MergeFields.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Trigger (string) maxLength
            if (this.Trigger != null && this.Trigger.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Trigger, length must be less than 1024.", new [] { "Trigger" });
            }

            // Trigger (string) pattern
            Regex regexTrigger = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexTrigger.Match(this.Trigger).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Trigger, must match a pattern of " + regexTrigger, new [] { "Trigger" });
            }

            yield break;
        }
    }
}
