/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Configuration for a Worker that executes a Horizon integration instance
    /// </summary>
    [DataContract(Name = "HorizonIntegration")]
    public partial class HorizonIntegration : IEquatable<HorizonIntegration>, IValidatableObject
    {
        /// <summary>
        /// The type of worker
        /// </summary>
        /// <value>The type of worker</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum HorizonIntegration for value: HorizonIntegration
            /// </summary>
            [EnumMember(Value = "HorizonIntegration")]
            HorizonIntegration = 1
        }


        /// <summary>
        /// The type of worker
        /// </summary>
        /// <value>The type of worker</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="HorizonIntegration" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected HorizonIntegration() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="HorizonIntegration" /> class.
        /// </summary>
        /// <param name="type">The type of worker (required).</param>
        /// <param name="integrationInstanceId">The id of the Horizon integration instance the worker executes. (required).</param>
        public HorizonIntegration(TypeEnum type = default(TypeEnum), string integrationInstanceId = default(string))
        {
            this.Type = type;
            // to ensure "integrationInstanceId" is required (not null)
            if (integrationInstanceId == null)
            {
                throw new ArgumentNullException("integrationInstanceId is a required property for HorizonIntegration and cannot be null");
            }
            this.IntegrationInstanceId = integrationInstanceId;
        }

        /// <summary>
        /// The id of the Horizon integration instance the worker executes.
        /// </summary>
        /// <value>The id of the Horizon integration instance the worker executes.</value>
        [DataMember(Name = "integrationInstanceId", IsRequired = true, EmitDefaultValue = true)]
        public string IntegrationInstanceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HorizonIntegration {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  IntegrationInstanceId: ").Append(IntegrationInstanceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HorizonIntegration);
        }

        /// <summary>
        /// Returns true if HorizonIntegration instances are equal
        /// </summary>
        /// <param name="input">Instance of HorizonIntegration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HorizonIntegration input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                ) && 
                (
                    this.IntegrationInstanceId == input.IntegrationInstanceId ||
                    (this.IntegrationInstanceId != null &&
                    this.IntegrationInstanceId.Equals(input.IntegrationInstanceId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                if (this.IntegrationInstanceId != null)
                {
                    hashCode = (hashCode * 59) + this.IntegrationInstanceId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // IntegrationInstanceId (string) maxLength
            if (this.IntegrationInstanceId != null && this.IntegrationInstanceId.Length > 512)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for IntegrationInstanceId, length must be less than 512.", new [] { "IntegrationInstanceId" });
            }

            // IntegrationInstanceId (string) minLength
            if (this.IntegrationInstanceId != null && this.IntegrationInstanceId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for IntegrationInstanceId, length must be greater than 1.", new [] { "IntegrationInstanceId" });
            }

            // IntegrationInstanceId (string) pattern
            Regex regexIntegrationInstanceId = new Regex(@"^[\s\S]*$", RegexOptions.CultureInvariant);
            if (false == regexIntegrationInstanceId.Match(this.IntegrationInstanceId).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for IntegrationInstanceId, must match a pattern of " + regexIntegrationInstanceId, new [] { "IntegrationInstanceId" });
            }

            yield break;
        }
    }
}
