/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// When a Schedule Launcher starts a run of its Workflow
    /// </summary>
    [DataContract(Name = "LauncherSchedule")]
    public partial class LauncherSchedule : IEquatable<LauncherSchedule>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LauncherSchedule" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LauncherSchedule() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LauncherSchedule" /> class.
        /// </summary>
        /// <param name="calendarContext">The name of the calendar context the schedule is read in, which must be one the Launcher declares (required).</param>
        /// <param name="recurrencePattern">recurrencePattern (required).</param>
        public LauncherSchedule(string calendarContext = default(string), RecurrencePattern recurrencePattern = default(RecurrencePattern))
        {
            // to ensure "calendarContext" is required (not null)
            if (calendarContext == null)
            {
                throw new ArgumentNullException("calendarContext is a required property for LauncherSchedule and cannot be null");
            }
            this.CalendarContext = calendarContext;
            // to ensure "recurrencePattern" is required (not null)
            if (recurrencePattern == null)
            {
                throw new ArgumentNullException("recurrencePattern is a required property for LauncherSchedule and cannot be null");
            }
            this.RecurrencePattern = recurrencePattern;
        }

        /// <summary>
        /// The name of the calendar context the schedule is read in, which must be one the Launcher declares
        /// </summary>
        /// <value>The name of the calendar context the schedule is read in, which must be one the Launcher declares</value>
        [DataMember(Name = "calendarContext", IsRequired = true, EmitDefaultValue = true)]
        public string CalendarContext { get; set; }

        /// <summary>
        /// Gets or Sets RecurrencePattern
        /// </summary>
        [DataMember(Name = "recurrencePattern", IsRequired = true, EmitDefaultValue = true)]
        public RecurrencePattern RecurrencePattern { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LauncherSchedule {\n");
            sb.Append("  CalendarContext: ").Append(CalendarContext).Append("\n");
            sb.Append("  RecurrencePattern: ").Append(RecurrencePattern).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LauncherSchedule);
        }

        /// <summary>
        /// Returns true if LauncherSchedule instances are equal
        /// </summary>
        /// <param name="input">Instance of LauncherSchedule to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LauncherSchedule input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CalendarContext == input.CalendarContext ||
                    (this.CalendarContext != null &&
                    this.CalendarContext.Equals(input.CalendarContext))
                ) && 
                (
                    this.RecurrencePattern == input.RecurrencePattern ||
                    (this.RecurrencePattern != null &&
                    this.RecurrencePattern.Equals(input.RecurrencePattern))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CalendarContext != null)
                {
                    hashCode = (hashCode * 59) + this.CalendarContext.GetHashCode();
                }
                if (this.RecurrencePattern != null)
                {
                    hashCode = (hashCode * 59) + this.RecurrencePattern.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CalendarContext (string) maxLength
            if (this.CalendarContext != null && this.CalendarContext.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CalendarContext, length must be less than 64.", new [] { "CalendarContext" });
            }

            // CalendarContext (string) minLength
            if (this.CalendarContext != null && this.CalendarContext.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CalendarContext, length must be greater than 1.", new [] { "CalendarContext" });
            }

            // CalendarContext (string) pattern
            Regex regexCalendarContext = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexCalendarContext.Match(this.CalendarContext).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CalendarContext, must match a pattern of " + regexCalendarContext, new [] { "CalendarContext" });
            }

            yield break;
        }
    }
}
