/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// A value a Launcher either gives as it is or takes from somewhere.              Exactly one of Finbourne.Workflow.WebApi.Common.Dto.Json.Launchers.LauncherMapping.SetTo or Finbourne.Workflow.WebApi.Common.Dto.Json.Launchers.LauncherMapping.MapFrom must be given. Only an Event Launcher has an event to take a value from, so a Schedule Launcher can only use Finbourne.Workflow.WebApi.Common.Dto.Json.Launchers.LauncherMapping.SetTo
    /// </summary>
    [DataContract(Name = "LauncherMapping")]
    public partial class LauncherMapping : IEquatable<LauncherMapping>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LauncherMapping" /> class.
        /// </summary>
        /// <param name="setTo">The value to use, given as it is.</param>
        /// <param name="mapFrom">The path the value is taken from, for example header.userId.</param>
        public LauncherMapping(string setTo = default(string), string mapFrom = default(string))
        {
            this.SetTo = setTo;
            this.MapFrom = mapFrom;
        }

        /// <summary>
        /// The value to use, given as it is
        /// </summary>
        /// <value>The value to use, given as it is</value>
        [DataMember(Name = "setTo", EmitDefaultValue = true)]
        public string SetTo { get; set; }

        /// <summary>
        /// The path the value is taken from, for example header.userId
        /// </summary>
        /// <value>The path the value is taken from, for example header.userId</value>
        [DataMember(Name = "mapFrom", EmitDefaultValue = true)]
        public string MapFrom { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LauncherMapping {\n");
            sb.Append("  SetTo: ").Append(SetTo).Append("\n");
            sb.Append("  MapFrom: ").Append(MapFrom).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LauncherMapping);
        }

        /// <summary>
        /// Returns true if LauncherMapping instances are equal
        /// </summary>
        /// <param name="input">Instance of LauncherMapping to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LauncherMapping input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SetTo == input.SetTo ||
                    (this.SetTo != null &&
                    this.SetTo.Equals(input.SetTo))
                ) && 
                (
                    this.MapFrom == input.MapFrom ||
                    (this.MapFrom != null &&
                    this.MapFrom.Equals(input.MapFrom))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SetTo != null)
                {
                    hashCode = (hashCode * 59) + this.SetTo.GetHashCode();
                }
                if (this.MapFrom != null)
                {
                    hashCode = (hashCode * 59) + this.MapFrom.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SetTo (string) maxLength
            if (this.SetTo != null && this.SetTo.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SetTo, length must be less than 1024.", new [] { "SetTo" });
            }

            // SetTo (string) minLength
            if (this.SetTo != null && this.SetTo.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SetTo, length must be greater than 0.", new [] { "SetTo" });
            }

            // MapFrom (string) maxLength
            if (this.MapFrom != null && this.MapFrom.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MapFrom, length must be less than 1024.", new [] { "MapFrom" });
            }

            // MapFrom (string) minLength
            if (this.MapFrom != null && this.MapFrom.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MapFrom, length must be greater than 0.", new [] { "MapFrom" });
            }

            yield break;
        }
    }
}
