/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Represents the relationship between a Launcher of a Workflow and the Task Definition it starts a run of
    /// </summary>
    [DataContract(Name = "LauncherEdge")]
    public partial class LauncherEdge : IEquatable<LauncherEdge>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LauncherEdge" /> class.
        /// </summary>
        /// <param name="launcherId">The identifier of the Launcher inside its Workflow.</param>
        /// <param name="targetTaskDefinition">targetTaskDefinition.</param>
        public LauncherEdge(string launcherId = default(string), VersionedTaskDefinitionId targetTaskDefinition = default(VersionedTaskDefinitionId))
        {
            this.LauncherId = launcherId;
            this.TargetTaskDefinition = targetTaskDefinition;
        }

        /// <summary>
        /// The identifier of the Launcher inside its Workflow
        /// </summary>
        /// <value>The identifier of the Launcher inside its Workflow</value>
        [DataMember(Name = "launcherId", EmitDefaultValue = true)]
        public string LauncherId { get; set; }

        /// <summary>
        /// Gets or Sets TargetTaskDefinition
        /// </summary>
        [DataMember(Name = "targetTaskDefinition", EmitDefaultValue = false)]
        public VersionedTaskDefinitionId TargetTaskDefinition { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LauncherEdge {\n");
            sb.Append("  LauncherId: ").Append(LauncherId).Append("\n");
            sb.Append("  TargetTaskDefinition: ").Append(TargetTaskDefinition).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LauncherEdge);
        }

        /// <summary>
        /// Returns true if LauncherEdge instances are equal
        /// </summary>
        /// <param name="input">Instance of LauncherEdge to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LauncherEdge input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.LauncherId == input.LauncherId ||
                    (this.LauncherId != null &&
                    this.LauncherId.Equals(input.LauncherId))
                ) && 
                (
                    this.TargetTaskDefinition == input.TargetTaskDefinition ||
                    (this.TargetTaskDefinition != null &&
                    this.TargetTaskDefinition.Equals(input.TargetTaskDefinition))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LauncherId != null)
                {
                    hashCode = (hashCode * 59) + this.LauncherId.GetHashCode();
                }
                if (this.TargetTaskDefinition != null)
                {
                    hashCode = (hashCode * 59) + this.TargetTaskDefinition.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
