/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// A Launcher, which starts a run of one Workflow either at the times a schedule gives or when a matching event arrives
    /// </summary>
    [DataContract(Name = "LauncherResponse")]
    public partial class LauncherResponse : IEquatable<LauncherResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LauncherResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LauncherResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LauncherResponse" /> class.
        /// </summary>
        /// <param name="workflowId">workflowId (required).</param>
        /// <param name="launcherId">The identifier of this Launcher inside its Workflow (required).</param>
        /// <param name="displayName">Human-readable name (required).</param>
        /// <param name="description">Human-readable description.</param>
        /// <param name="status">The current status of the Launcher. One of - Active, Inactive (required).</param>
        /// <param name="launcherDetails">launcherDetails (required).</param>
        /// <param name="summaries">summaries.</param>
        /// <param name="varVersion">varVersion.</param>
        public LauncherResponse(ResourceId workflowId = default(ResourceId), string launcherId = default(string), string displayName = default(string), string description = default(string), string status = default(string), LauncherDetailsResponse launcherDetails = default(LauncherDetailsResponse), LauncherSummaries summaries = default(LauncherSummaries), VersionInfo varVersion = default(VersionInfo))
        {
            // to ensure "workflowId" is required (not null)
            if (workflowId == null)
            {
                throw new ArgumentNullException("workflowId is a required property for LauncherResponse and cannot be null");
            }
            this.WorkflowId = workflowId;
            // to ensure "launcherId" is required (not null)
            if (launcherId == null)
            {
                throw new ArgumentNullException("launcherId is a required property for LauncherResponse and cannot be null");
            }
            this.LauncherId = launcherId;
            // to ensure "displayName" is required (not null)
            if (displayName == null)
            {
                throw new ArgumentNullException("displayName is a required property for LauncherResponse and cannot be null");
            }
            this.DisplayName = displayName;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for LauncherResponse and cannot be null");
            }
            this.Status = status;
            // to ensure "launcherDetails" is required (not null)
            if (launcherDetails == null)
            {
                throw new ArgumentNullException("launcherDetails is a required property for LauncherResponse and cannot be null");
            }
            this.LauncherDetails = launcherDetails;
            this.Description = description;
            this.Summaries = summaries;
            this.VarVersion = varVersion;
        }

        /// <summary>
        /// Gets or Sets WorkflowId
        /// </summary>
        [DataMember(Name = "workflowId", IsRequired = true, EmitDefaultValue = true)]
        public ResourceId WorkflowId { get; set; }

        /// <summary>
        /// The identifier of this Launcher inside its Workflow
        /// </summary>
        /// <value>The identifier of this Launcher inside its Workflow</value>
        [DataMember(Name = "launcherId", IsRequired = true, EmitDefaultValue = true)]
        public string LauncherId { get; set; }

        /// <summary>
        /// Human-readable name
        /// </summary>
        /// <value>Human-readable name</value>
        [DataMember(Name = "displayName", IsRequired = true, EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Human-readable description
        /// </summary>
        /// <value>Human-readable description</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// The current status of the Launcher. One of - Active, Inactive
        /// </summary>
        /// <value>The current status of the Launcher. One of - Active, Inactive</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets LauncherDetails
        /// </summary>
        [DataMember(Name = "launcherDetails", IsRequired = true, EmitDefaultValue = true)]
        public LauncherDetailsResponse LauncherDetails { get; set; }

        /// <summary>
        /// Gets or Sets Summaries
        /// </summary>
        [DataMember(Name = "summaries", EmitDefaultValue = false)]
        public LauncherSummaries Summaries { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public VersionInfo VarVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LauncherResponse {\n");
            sb.Append("  WorkflowId: ").Append(WorkflowId).Append("\n");
            sb.Append("  LauncherId: ").Append(LauncherId).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  LauncherDetails: ").Append(LauncherDetails).Append("\n");
            sb.Append("  Summaries: ").Append(Summaries).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LauncherResponse);
        }

        /// <summary>
        /// Returns true if LauncherResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of LauncherResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LauncherResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.WorkflowId == input.WorkflowId ||
                    (this.WorkflowId != null &&
                    this.WorkflowId.Equals(input.WorkflowId))
                ) && 
                (
                    this.LauncherId == input.LauncherId ||
                    (this.LauncherId != null &&
                    this.LauncherId.Equals(input.LauncherId))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.LauncherDetails == input.LauncherDetails ||
                    (this.LauncherDetails != null &&
                    this.LauncherDetails.Equals(input.LauncherDetails))
                ) && 
                (
                    this.Summaries == input.Summaries ||
                    (this.Summaries != null &&
                    this.Summaries.Equals(input.Summaries))
                ) && 
                (
                    this.VarVersion == input.VarVersion ||
                    (this.VarVersion != null &&
                    this.VarVersion.Equals(input.VarVersion))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.WorkflowId != null)
                {
                    hashCode = (hashCode * 59) + this.WorkflowId.GetHashCode();
                }
                if (this.LauncherId != null)
                {
                    hashCode = (hashCode * 59) + this.LauncherId.GetHashCode();
                }
                if (this.DisplayName != null)
                {
                    hashCode = (hashCode * 59) + this.DisplayName.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                if (this.LauncherDetails != null)
                {
                    hashCode = (hashCode * 59) + this.LauncherDetails.GetHashCode();
                }
                if (this.Summaries != null)
                {
                    hashCode = (hashCode * 59) + this.Summaries.GetHashCode();
                }
                if (this.VarVersion != null)
                {
                    hashCode = (hashCode * 59) + this.VarVersion.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // LauncherId (string) minLength
            if (this.LauncherId != null && this.LauncherId.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LauncherId, length must be greater than 1.", new [] { "LauncherId" });
            }

            // DisplayName (string) minLength
            if (this.DisplayName != null && this.DisplayName.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DisplayName, length must be greater than 1.", new [] { "DisplayName" });
            }

            // Status (string) minLength
            if (this.Status != null && this.Status.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Status, length must be greater than 1.", new [] { "Status" });
            }

            yield break;
        }
    }
}
