/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Behaviour applied to a new child task candidate whose stacking key matches an existing (non-terminal) child task
    /// </summary>
    [DataContract(Name = "NewTasksRecurringConfiguration")]
    public partial class NewTasksRecurringConfiguration : IEquatable<NewTasksRecurringConfiguration>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewTasksRecurringConfiguration" /> class.
        /// </summary>
        /// <param name="doNotCreate">When true, the new child task will not be created.</param>
        /// <param name="initialTriggerOverride">When DoNotCreate is false, the new child task will be created with this trigger instead of the ChildTaskConfiguration&#39;s InitialTrigger.</param>
        public NewTasksRecurringConfiguration(bool doNotCreate = default(bool), string initialTriggerOverride = default(string))
        {
            this.DoNotCreate = doNotCreate;
            this.InitialTriggerOverride = initialTriggerOverride;
        }

        /// <summary>
        /// When true, the new child task will not be created
        /// </summary>
        /// <value>When true, the new child task will not be created</value>
        [DataMember(Name = "doNotCreate", EmitDefaultValue = true)]
        public bool DoNotCreate { get; set; }

        /// <summary>
        /// When DoNotCreate is false, the new child task will be created with this trigger instead of the ChildTaskConfiguration&#39;s InitialTrigger
        /// </summary>
        /// <value>When DoNotCreate is false, the new child task will be created with this trigger instead of the ChildTaskConfiguration&#39;s InitialTrigger</value>
        [DataMember(Name = "initialTriggerOverride", EmitDefaultValue = true)]
        public string InitialTriggerOverride { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NewTasksRecurringConfiguration {\n");
            sb.Append("  DoNotCreate: ").Append(DoNotCreate).Append("\n");
            sb.Append("  InitialTriggerOverride: ").Append(InitialTriggerOverride).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NewTasksRecurringConfiguration);
        }

        /// <summary>
        /// Returns true if NewTasksRecurringConfiguration instances are equal
        /// </summary>
        /// <param name="input">Instance of NewTasksRecurringConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NewTasksRecurringConfiguration input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DoNotCreate == input.DoNotCreate ||
                    this.DoNotCreate.Equals(input.DoNotCreate)
                ) && 
                (
                    this.InitialTriggerOverride == input.InitialTriggerOverride ||
                    (this.InitialTriggerOverride != null &&
                    this.InitialTriggerOverride.Equals(input.InitialTriggerOverride))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.DoNotCreate.GetHashCode();
                if (this.InitialTriggerOverride != null)
                {
                    hashCode = (hashCode * 59) + this.InitialTriggerOverride.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // InitialTriggerOverride (string) maxLength
            if (this.InitialTriggerOverride != null && this.InitialTriggerOverride.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for InitialTriggerOverride, length must be less than 1024.", new [] { "InitialTriggerOverride" });
            }

            // InitialTriggerOverride (string) pattern
            Regex regexInitialTriggerOverride = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexInitialTriggerOverride.Match(this.InitialTriggerOverride).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for InitialTriggerOverride, must match a pattern of " + regexInitialTriggerOverride, new [] { "InitialTriggerOverride" });
            }

            yield break;
        }
    }
}
