/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Defines how re-run results for a given (child) TaskDefinitionId should be reconciled against existing (non-terminal) child tasks of the same parent Task instance.
    /// </summary>
    [DataContract(Name = "ReRunConfiguration")]
    public partial class ReRunConfiguration : IEquatable<ReRunConfiguration>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReRunConfiguration" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReRunConfiguration() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReRunConfiguration" /> class.
        /// </summary>
        /// <param name="taskDefinitionId">taskDefinitionId (required).</param>
        /// <param name="resultsRecurring">resultsRecurring (required).</param>
        /// <param name="resultsNotRecurring">resultsNotRecurring (required).</param>
        public ReRunConfiguration(ResourceId taskDefinitionId = default(ResourceId), ResultsRecurringConfiguration resultsRecurring = default(ResultsRecurringConfiguration), ResultsNotRecurringConfiguration resultsNotRecurring = default(ResultsNotRecurringConfiguration))
        {
            // to ensure "taskDefinitionId" is required (not null)
            if (taskDefinitionId == null)
            {
                throw new ArgumentNullException("taskDefinitionId is a required property for ReRunConfiguration and cannot be null");
            }
            this.TaskDefinitionId = taskDefinitionId;
            // to ensure "resultsRecurring" is required (not null)
            if (resultsRecurring == null)
            {
                throw new ArgumentNullException("resultsRecurring is a required property for ReRunConfiguration and cannot be null");
            }
            this.ResultsRecurring = resultsRecurring;
            // to ensure "resultsNotRecurring" is required (not null)
            if (resultsNotRecurring == null)
            {
                throw new ArgumentNullException("resultsNotRecurring is a required property for ReRunConfiguration and cannot be null");
            }
            this.ResultsNotRecurring = resultsNotRecurring;
        }

        /// <summary>
        /// Gets or Sets TaskDefinitionId
        /// </summary>
        [DataMember(Name = "taskDefinitionId", IsRequired = true, EmitDefaultValue = true)]
        public ResourceId TaskDefinitionId { get; set; }

        /// <summary>
        /// Gets or Sets ResultsRecurring
        /// </summary>
        [DataMember(Name = "resultsRecurring", IsRequired = true, EmitDefaultValue = true)]
        public ResultsRecurringConfiguration ResultsRecurring { get; set; }

        /// <summary>
        /// Gets or Sets ResultsNotRecurring
        /// </summary>
        [DataMember(Name = "resultsNotRecurring", IsRequired = true, EmitDefaultValue = true)]
        public ResultsNotRecurringConfiguration ResultsNotRecurring { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReRunConfiguration {\n");
            sb.Append("  TaskDefinitionId: ").Append(TaskDefinitionId).Append("\n");
            sb.Append("  ResultsRecurring: ").Append(ResultsRecurring).Append("\n");
            sb.Append("  ResultsNotRecurring: ").Append(ResultsNotRecurring).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReRunConfiguration);
        }

        /// <summary>
        /// Returns true if ReRunConfiguration instances are equal
        /// </summary>
        /// <param name="input">Instance of ReRunConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReRunConfiguration input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TaskDefinitionId == input.TaskDefinitionId ||
                    (this.TaskDefinitionId != null &&
                    this.TaskDefinitionId.Equals(input.TaskDefinitionId))
                ) && 
                (
                    this.ResultsRecurring == input.ResultsRecurring ||
                    (this.ResultsRecurring != null &&
                    this.ResultsRecurring.Equals(input.ResultsRecurring))
                ) && 
                (
                    this.ResultsNotRecurring == input.ResultsNotRecurring ||
                    (this.ResultsNotRecurring != null &&
                    this.ResultsNotRecurring.Equals(input.ResultsNotRecurring))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TaskDefinitionId != null)
                {
                    hashCode = (hashCode * 59) + this.TaskDefinitionId.GetHashCode();
                }
                if (this.ResultsRecurring != null)
                {
                    hashCode = (hashCode * 59) + this.ResultsRecurring.GetHashCode();
                }
                if (this.ResultsNotRecurring != null)
                {
                    hashCode = (hashCode * 59) + this.ResultsNotRecurring.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
