/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Behaviour applied to new child task candidates, and to existing child tasks, when their stacking keys match one another
    /// </summary>
    [DataContract(Name = "ResultsRecurringConfiguration")]
    public partial class ResultsRecurringConfiguration : IEquatable<ResultsRecurringConfiguration>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResultsRecurringConfiguration" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResultsRecurringConfiguration() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResultsRecurringConfiguration" /> class.
        /// </summary>
        /// <param name="newTasks">newTasks (required).</param>
        /// <param name="existingTasks">existingTasks (required).</param>
        public ResultsRecurringConfiguration(NewTasksRecurringConfiguration newTasks = default(NewTasksRecurringConfiguration), ExistingTasksRecurringConfiguration existingTasks = default(ExistingTasksRecurringConfiguration))
        {
            // to ensure "newTasks" is required (not null)
            if (newTasks == null)
            {
                throw new ArgumentNullException("newTasks is a required property for ResultsRecurringConfiguration and cannot be null");
            }
            this.NewTasks = newTasks;
            // to ensure "existingTasks" is required (not null)
            if (existingTasks == null)
            {
                throw new ArgumentNullException("existingTasks is a required property for ResultsRecurringConfiguration and cannot be null");
            }
            this.ExistingTasks = existingTasks;
        }

        /// <summary>
        /// Gets or Sets NewTasks
        /// </summary>
        [DataMember(Name = "newTasks", IsRequired = true, EmitDefaultValue = true)]
        public NewTasksRecurringConfiguration NewTasks { get; set; }

        /// <summary>
        /// Gets or Sets ExistingTasks
        /// </summary>
        [DataMember(Name = "existingTasks", IsRequired = true, EmitDefaultValue = true)]
        public ExistingTasksRecurringConfiguration ExistingTasks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResultsRecurringConfiguration {\n");
            sb.Append("  NewTasks: ").Append(NewTasks).Append("\n");
            sb.Append("  ExistingTasks: ").Append(ExistingTasks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ResultsRecurringConfiguration);
        }

        /// <summary>
        /// Returns true if ResultsRecurringConfiguration instances are equal
        /// </summary>
        /// <param name="input">Instance of ResultsRecurringConfiguration to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ResultsRecurringConfiguration input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.NewTasks == input.NewTasks ||
                    (this.NewTasks != null &&
                    this.NewTasks.Equals(input.NewTasks))
                ) && 
                (
                    this.ExistingTasks == input.ExistingTasks ||
                    (this.ExistingTasks != null &&
                    this.ExistingTasks.Equals(input.ExistingTasks))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NewTasks != null)
                {
                    hashCode = (hashCode * 59) + this.NewTasks.GetHashCode();
                }
                if (this.ExistingTasks != null)
                {
                    hashCode = (hashCode * 59) + this.ExistingTasks.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
