/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Represents an adjustment to the scheduled time of an EventHandler. Only relevant for EventHandlers with a  Finbourne.Workflow.WebApi.Common.Dto.Json.EventHandlers.ScheduleMatchingPattern
    /// </summary>
    [DataContract(Name = "ScheduledTimeAdjustment")]
    public partial class ScheduledTimeAdjustment : IEquatable<ScheduledTimeAdjustment>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduledTimeAdjustment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScheduledTimeAdjustment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduledTimeAdjustment" /> class.
        /// </summary>
        /// <param name="dateAdjustment">dateAdjustment (required).</param>
        /// <param name="timeAdjustment">timeAdjustment (required).</param>
        public ScheduledTimeAdjustment(DateAdjustment dateAdjustment = default(DateAdjustment), TimeAdjustment timeAdjustment = default(TimeAdjustment))
        {
            // to ensure "dateAdjustment" is required (not null)
            if (dateAdjustment == null)
            {
                throw new ArgumentNullException("dateAdjustment is a required property for ScheduledTimeAdjustment and cannot be null");
            }
            this.DateAdjustment = dateAdjustment;
            // to ensure "timeAdjustment" is required (not null)
            if (timeAdjustment == null)
            {
                throw new ArgumentNullException("timeAdjustment is a required property for ScheduledTimeAdjustment and cannot be null");
            }
            this.TimeAdjustment = timeAdjustment;
        }

        /// <summary>
        /// Gets or Sets DateAdjustment
        /// </summary>
        [DataMember(Name = "dateAdjustment", IsRequired = true, EmitDefaultValue = true)]
        public DateAdjustment DateAdjustment { get; set; }

        /// <summary>
        /// Gets or Sets TimeAdjustment
        /// </summary>
        [DataMember(Name = "timeAdjustment", IsRequired = true, EmitDefaultValue = true)]
        public TimeAdjustment TimeAdjustment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScheduledTimeAdjustment {\n");
            sb.Append("  DateAdjustment: ").Append(DateAdjustment).Append("\n");
            sb.Append("  TimeAdjustment: ").Append(TimeAdjustment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScheduledTimeAdjustment);
        }

        /// <summary>
        /// Returns true if ScheduledTimeAdjustment instances are equal
        /// </summary>
        /// <param name="input">Instance of ScheduledTimeAdjustment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduledTimeAdjustment input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DateAdjustment == input.DateAdjustment ||
                    (this.DateAdjustment != null &&
                    this.DateAdjustment.Equals(input.DateAdjustment))
                ) && 
                (
                    this.TimeAdjustment == input.TimeAdjustment ||
                    (this.TimeAdjustment != null &&
                    this.TimeAdjustment.Equals(input.TimeAdjustment))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DateAdjustment != null)
                {
                    hashCode = (hashCode * 59) + this.DateAdjustment.GetHashCode();
                }
                if (this.TimeAdjustment != null)
                {
                    hashCode = (hashCode * 59) + this.TimeAdjustment.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
