/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// The Schedule Matching Pattern to trigger on
    /// </summary>
    [DataContract(Name = "ScheduleMatchingPattern")]
    public partial class ScheduleMatchingPattern : IEquatable<ScheduleMatchingPattern>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleMatchingPattern" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScheduleMatchingPattern() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleMatchingPattern" /> class.
        /// </summary>
        /// <param name="context">context (required).</param>
        /// <param name="recurrencePattern">recurrencePattern (required).</param>
        public ScheduleMatchingPattern(ScheduleMatchingPatternContext context = default(ScheduleMatchingPatternContext), RecurrencePattern recurrencePattern = default(RecurrencePattern))
        {
            // to ensure "context" is required (not null)
            if (context == null)
            {
                throw new ArgumentNullException("context is a required property for ScheduleMatchingPattern and cannot be null");
            }
            this.Context = context;
            // to ensure "recurrencePattern" is required (not null)
            if (recurrencePattern == null)
            {
                throw new ArgumentNullException("recurrencePattern is a required property for ScheduleMatchingPattern and cannot be null");
            }
            this.RecurrencePattern = recurrencePattern;
        }

        /// <summary>
        /// Gets or Sets Context
        /// </summary>
        [DataMember(Name = "context", IsRequired = true, EmitDefaultValue = true)]
        public ScheduleMatchingPatternContext Context { get; set; }

        /// <summary>
        /// Gets or Sets RecurrencePattern
        /// </summary>
        [DataMember(Name = "recurrencePattern", IsRequired = true, EmitDefaultValue = true)]
        public RecurrencePattern RecurrencePattern { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScheduleMatchingPattern {\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("  RecurrencePattern: ").Append(RecurrencePattern).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScheduleMatchingPattern);
        }

        /// <summary>
        /// Returns true if ScheduleMatchingPattern instances are equal
        /// </summary>
        /// <param name="input">Instance of ScheduleMatchingPattern to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduleMatchingPattern input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Context == input.Context ||
                    (this.Context != null &&
                    this.Context.Equals(input.Context))
                ) && 
                (
                    this.RecurrencePattern == input.RecurrencePattern ||
                    (this.RecurrencePattern != null &&
                    this.RecurrencePattern.Equals(input.RecurrencePattern))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Context != null)
                {
                    hashCode = (hashCode * 59) + this.Context.GetHashCode();
                }
                if (this.RecurrencePattern != null)
                {
                    hashCode = (hashCode * 59) + this.RecurrencePattern.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
