/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// A Schedule Launcher, which starts a run of its Workflow at the times a recurrence pattern gives
    /// </summary>
    [DataContract(Name = "ScheduleLauncherDetailsResponse")]
    public partial class ScheduleLauncherDetailsResponse : IEquatable<ScheduleLauncherDetailsResponse>, IValidatableObject
    {
        /// <summary>
        /// Defines LauncherType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LauncherTypeEnum
        {
            /// <summary>
            /// Enum Schedule for value: Schedule
            /// </summary>
            [EnumMember(Value = "Schedule")]
            Schedule = 1
        }


        /// <summary>
        /// Gets or Sets LauncherType
        /// </summary>
        [DataMember(Name = "launcherType", EmitDefaultValue = true)]
        public LauncherTypeEnum? LauncherType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleLauncherDetailsResponse" /> class.
        /// </summary>
        /// <param name="launcherType">launcherType.</param>
        /// <param name="schedule">schedule.</param>
        /// <param name="calendarContexts">The named time zones and holiday calendars this Launcher works in.              Only a Schedule Launcher works in a calendar context.</param>
        /// <param name="mapTaskFields">Fields of the root task filled from the instant the schedule fired, keyed by the field name on the root task definition.</param>
        /// <param name="runAsUserId">runAsUserId.</param>
        /// <param name="setTaskFields">Fields of the root task set to a fixed value, keyed by the field name on the root task definition.</param>
        /// <param name="setCorrelationIds">Correlation IDs put on the root task as given.</param>
        /// <param name="initialTrigger">The trigger given to the root task once it is made and all of its fields are filled, or null when the root task is left in its initial state.</param>
        public ScheduleLauncherDetailsResponse(LauncherTypeEnum ?launcherType = default(LauncherTypeEnum?), LauncherSchedule schedule = default(LauncherSchedule), List<CalendarContext> calendarContexts = default(List<CalendarContext>), Dictionary<string, ScheduleTaskFieldMapping> mapTaskFields = default(Dictionary<string, ScheduleTaskFieldMapping>), LauncherMapping runAsUserId = default(LauncherMapping), Dictionary<string, Object> setTaskFields = default(Dictionary<string, Object>), List<string> setCorrelationIds = default(List<string>), string initialTrigger = default(string))
        {
            this.LauncherType = launcherType;
            this.Schedule = schedule;
            this.CalendarContexts = calendarContexts;
            this.MapTaskFields = mapTaskFields;
            this.RunAsUserId = runAsUserId;
            this.SetTaskFields = setTaskFields;
            this.SetCorrelationIds = setCorrelationIds;
            this.InitialTrigger = initialTrigger;
        }

        /// <summary>
        /// Gets or Sets Schedule
        /// </summary>
        [DataMember(Name = "schedule", EmitDefaultValue = false)]
        public LauncherSchedule Schedule { get; set; }

        /// <summary>
        /// The named time zones and holiday calendars this Launcher works in.              Only a Schedule Launcher works in a calendar context
        /// </summary>
        /// <value>The named time zones and holiday calendars this Launcher works in.              Only a Schedule Launcher works in a calendar context</value>
        [DataMember(Name = "calendarContexts", EmitDefaultValue = true)]
        public List<CalendarContext> CalendarContexts { get; set; }

        /// <summary>
        /// Fields of the root task filled from the instant the schedule fired, keyed by the field name on the root task definition
        /// </summary>
        /// <value>Fields of the root task filled from the instant the schedule fired, keyed by the field name on the root task definition</value>
        [DataMember(Name = "mapTaskFields", EmitDefaultValue = true)]
        public Dictionary<string, ScheduleTaskFieldMapping> MapTaskFields { get; set; }

        /// <summary>
        /// Gets or Sets RunAsUserId
        /// </summary>
        [DataMember(Name = "runAsUserId", EmitDefaultValue = false)]
        public LauncherMapping RunAsUserId { get; set; }

        /// <summary>
        /// Fields of the root task set to a fixed value, keyed by the field name on the root task definition
        /// </summary>
        /// <value>Fields of the root task set to a fixed value, keyed by the field name on the root task definition</value>
        [DataMember(Name = "setTaskFields", EmitDefaultValue = true)]
        public Dictionary<string, Object> SetTaskFields { get; set; }

        /// <summary>
        /// Correlation IDs put on the root task as given
        /// </summary>
        /// <value>Correlation IDs put on the root task as given</value>
        [DataMember(Name = "setCorrelationIds", EmitDefaultValue = true)]
        public List<string> SetCorrelationIds { get; set; }

        /// <summary>
        /// The trigger given to the root task once it is made and all of its fields are filled, or null when the root task is left in its initial state
        /// </summary>
        /// <value>The trigger given to the root task once it is made and all of its fields are filled, or null when the root task is left in its initial state</value>
        [DataMember(Name = "initialTrigger", EmitDefaultValue = true)]
        public string InitialTrigger { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScheduleLauncherDetailsResponse {\n");
            sb.Append("  LauncherType: ").Append(LauncherType).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  CalendarContexts: ").Append(CalendarContexts).Append("\n");
            sb.Append("  MapTaskFields: ").Append(MapTaskFields).Append("\n");
            sb.Append("  RunAsUserId: ").Append(RunAsUserId).Append("\n");
            sb.Append("  SetTaskFields: ").Append(SetTaskFields).Append("\n");
            sb.Append("  SetCorrelationIds: ").Append(SetCorrelationIds).Append("\n");
            sb.Append("  InitialTrigger: ").Append(InitialTrigger).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScheduleLauncherDetailsResponse);
        }

        /// <summary>
        /// Returns true if ScheduleLauncherDetailsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ScheduleLauncherDetailsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduleLauncherDetailsResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.LauncherType == input.LauncherType ||
                    this.LauncherType.Equals(input.LauncherType)
                ) && 
                (
                    this.Schedule == input.Schedule ||
                    (this.Schedule != null &&
                    this.Schedule.Equals(input.Schedule))
                ) && 
                (
                    this.CalendarContexts == input.CalendarContexts ||
                    this.CalendarContexts != null &&
                    input.CalendarContexts != null &&
                    this.CalendarContexts.SequenceEqual(input.CalendarContexts)
                ) && 
                (
                    this.MapTaskFields == input.MapTaskFields ||
                    this.MapTaskFields != null &&
                    input.MapTaskFields != null &&
                    this.MapTaskFields.SequenceEqual(input.MapTaskFields)
                ) && 
                (
                    this.RunAsUserId == input.RunAsUserId ||
                    (this.RunAsUserId != null &&
                    this.RunAsUserId.Equals(input.RunAsUserId))
                ) && 
                (
                    this.SetTaskFields == input.SetTaskFields ||
                    this.SetTaskFields != null &&
                    input.SetTaskFields != null &&
                    this.SetTaskFields.SequenceEqual(input.SetTaskFields)
                ) && 
                (
                    this.SetCorrelationIds == input.SetCorrelationIds ||
                    this.SetCorrelationIds != null &&
                    input.SetCorrelationIds != null &&
                    this.SetCorrelationIds.SequenceEqual(input.SetCorrelationIds)
                ) && 
                (
                    this.InitialTrigger == input.InitialTrigger ||
                    (this.InitialTrigger != null &&
                    this.InitialTrigger.Equals(input.InitialTrigger))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.LauncherType.GetHashCode();
                if (this.Schedule != null)
                {
                    hashCode = (hashCode * 59) + this.Schedule.GetHashCode();
                }
                if (this.CalendarContexts != null)
                {
                    hashCode = (hashCode * 59) + this.CalendarContexts.GetHashCode();
                }
                if (this.MapTaskFields != null)
                {
                    hashCode = (hashCode * 59) + this.MapTaskFields.GetHashCode();
                }
                if (this.RunAsUserId != null)
                {
                    hashCode = (hashCode * 59) + this.RunAsUserId.GetHashCode();
                }
                if (this.SetTaskFields != null)
                {
                    hashCode = (hashCode * 59) + this.SetTaskFields.GetHashCode();
                }
                if (this.SetCorrelationIds != null)
                {
                    hashCode = (hashCode * 59) + this.SetCorrelationIds.GetHashCode();
                }
                if (this.InitialTrigger != null)
                {
                    hashCode = (hashCode * 59) + this.InitialTrigger.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
