/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Specific Month Regularity
    /// </summary>
    [DataContract(Name = "SpecificMonthRegularity")]
    public partial class SpecificMonthRegularity : IEquatable<SpecificMonthRegularity>, IValidatableObject
    {
        /// <summary>
        /// The type of Date Regularity
        /// </summary>
        /// <value>The type of Date Regularity</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum SpecificMonth for value: SpecificMonth
            /// </summary>
            [EnumMember(Value = "SpecificMonth")]
            SpecificMonth = 1
        }


        /// <summary>
        /// The type of Date Regularity
        /// </summary>
        /// <value>The type of Date Regularity</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SpecificMonthRegularity" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SpecificMonthRegularity() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SpecificMonthRegularity" /> class.
        /// </summary>
        /// <param name="frequency">The frequency of the Specific Month Regularity (required).</param>
        /// <param name="daysOfMonth">Days of the month (required).</param>
        /// <param name="type">The type of Date Regularity (required).</param>
        public SpecificMonthRegularity(int frequency = default(int), List<int> daysOfMonth = default(List<int>), TypeEnum type = default(TypeEnum))
        {
            this.Frequency = frequency;
            // to ensure "daysOfMonth" is required (not null)
            if (daysOfMonth == null)
            {
                throw new ArgumentNullException("daysOfMonth is a required property for SpecificMonthRegularity and cannot be null");
            }
            this.DaysOfMonth = daysOfMonth;
            this.Type = type;
        }

        /// <summary>
        /// The frequency of the Specific Month Regularity
        /// </summary>
        /// <value>The frequency of the Specific Month Regularity</value>
        [DataMember(Name = "frequency", IsRequired = true, EmitDefaultValue = true)]
        public int Frequency { get; set; }

        /// <summary>
        /// Days of the month
        /// </summary>
        /// <value>Days of the month</value>
        [DataMember(Name = "daysOfMonth", IsRequired = true, EmitDefaultValue = true)]
        public List<int> DaysOfMonth { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpecificMonthRegularity {\n");
            sb.Append("  Frequency: ").Append(Frequency).Append("\n");
            sb.Append("  DaysOfMonth: ").Append(DaysOfMonth).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpecificMonthRegularity);
        }

        /// <summary>
        /// Returns true if SpecificMonthRegularity instances are equal
        /// </summary>
        /// <param name="input">Instance of SpecificMonthRegularity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpecificMonthRegularity input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Frequency == input.Frequency ||
                    this.Frequency.Equals(input.Frequency)
                ) && 
                (
                    this.DaysOfMonth == input.DaysOfMonth ||
                    this.DaysOfMonth != null &&
                    input.DaysOfMonth != null &&
                    this.DaysOfMonth.SequenceEqual(input.DaysOfMonth)
                ) && 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Frequency.GetHashCode();
                if (this.DaysOfMonth != null)
                {
                    hashCode = (hashCode * 59) + this.DaysOfMonth.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Frequency (int) maximum
            if (this.Frequency > (int)100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Frequency, must be a value less than or equal to 100.", new [] { "Frequency" });
            }

            // Frequency (int) minimum
            if (this.Frequency < (int)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Frequency, must be a value greater than or equal to 1.", new [] { "Frequency" });
            }

            yield break;
        }
    }
}
