/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// A Task Definition Id with an optional asAt timestamp identifying a specific version
    /// </summary>
    [DataContract(Name = "VersionedTaskDefinitionId")]
    public partial class VersionedTaskDefinitionId : IEquatable<VersionedTaskDefinitionId>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VersionedTaskDefinitionId" /> class.
        /// </summary>
        /// <param name="taskDefinitionId">taskDefinitionId.</param>
        /// <param name="taskDefinitionAsAt">The asAt time of this version of the Task Definition. Null means the latest version..</param>
        public VersionedTaskDefinitionId(ResourceId taskDefinitionId = default(ResourceId), DateTimeOffset? taskDefinitionAsAt = default(DateTimeOffset?))
        {
            this.TaskDefinitionId = taskDefinitionId;
            this.TaskDefinitionAsAt = taskDefinitionAsAt;
        }

        /// <summary>
        /// Gets or Sets TaskDefinitionId
        /// </summary>
        [DataMember(Name = "taskDefinitionId", EmitDefaultValue = false)]
        public ResourceId TaskDefinitionId { get; set; }

        /// <summary>
        /// The asAt time of this version of the Task Definition. Null means the latest version.
        /// </summary>
        /// <value>The asAt time of this version of the Task Definition. Null means the latest version.</value>
        [DataMember(Name = "taskDefinitionAsAt", EmitDefaultValue = true)]
        public DateTimeOffset? TaskDefinitionAsAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VersionedTaskDefinitionId {\n");
            sb.Append("  TaskDefinitionId: ").Append(TaskDefinitionId).Append("\n");
            sb.Append("  TaskDefinitionAsAt: ").Append(TaskDefinitionAsAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VersionedTaskDefinitionId);
        }

        /// <summary>
        /// Returns true if VersionedTaskDefinitionId instances are equal
        /// </summary>
        /// <param name="input">Instance of VersionedTaskDefinitionId to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VersionedTaskDefinitionId input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TaskDefinitionId == input.TaskDefinitionId ||
                    (this.TaskDefinitionId != null &&
                    this.TaskDefinitionId.Equals(input.TaskDefinitionId))
                ) && 
                (
                    this.TaskDefinitionAsAt == input.TaskDefinitionAsAt ||
                    (this.TaskDefinitionAsAt != null &&
                    this.TaskDefinitionAsAt.Equals(input.TaskDefinitionAsAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TaskDefinitionId != null)
                {
                    hashCode = (hashCode * 59) + this.TaskDefinitionId.GetHashCode();
                }
                if (this.TaskDefinitionAsAt != null)
                {
                    hashCode = (hashCode * 59) + this.TaskDefinitionAsAt.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
