/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Week Regularity
    /// </summary>
    [DataContract(Name = "WeekRegularity")]
    public partial class WeekRegularity : IEquatable<WeekRegularity>, IValidatableObject
    {
        /// <summary>
        /// The type of Date Regularity
        /// </summary>
        /// <value>The type of Date Regularity</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Week for value: Week
            /// </summary>
            [EnumMember(Value = "Week")]
            Week = 1
        }


        /// <summary>
        /// The type of Date Regularity
        /// </summary>
        /// <value>The type of Date Regularity</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="WeekRegularity" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WeekRegularity() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WeekRegularity" /> class.
        /// </summary>
        /// <param name="frequency">The frequency of the Week Regularity. For example, a value of 2 indicates every 2 weeks (required).</param>
        /// <param name="daysOfWeek">Days of the week. One or more of - Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday (required).</param>
        /// <param name="type">The type of Date Regularity (required).</param>
        public WeekRegularity(int frequency = default(int), List<string> daysOfWeek = default(List<string>), TypeEnum type = default(TypeEnum))
        {
            this.Frequency = frequency;
            // to ensure "daysOfWeek" is required (not null)
            if (daysOfWeek == null)
            {
                throw new ArgumentNullException("daysOfWeek is a required property for WeekRegularity and cannot be null");
            }
            this.DaysOfWeek = daysOfWeek;
            this.Type = type;
        }

        /// <summary>
        /// The frequency of the Week Regularity. For example, a value of 2 indicates every 2 weeks
        /// </summary>
        /// <value>The frequency of the Week Regularity. For example, a value of 2 indicates every 2 weeks</value>
        [DataMember(Name = "frequency", IsRequired = true, EmitDefaultValue = true)]
        public int Frequency { get; set; }

        /// <summary>
        /// Days of the week. One or more of - Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday
        /// </summary>
        /// <value>Days of the week. One or more of - Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday</value>
        [DataMember(Name = "daysOfWeek", IsRequired = true, EmitDefaultValue = true)]
        public List<string> DaysOfWeek { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WeekRegularity {\n");
            sb.Append("  Frequency: ").Append(Frequency).Append("\n");
            sb.Append("  DaysOfWeek: ").Append(DaysOfWeek).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WeekRegularity);
        }

        /// <summary>
        /// Returns true if WeekRegularity instances are equal
        /// </summary>
        /// <param name="input">Instance of WeekRegularity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WeekRegularity input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Frequency == input.Frequency ||
                    this.Frequency.Equals(input.Frequency)
                ) && 
                (
                    this.DaysOfWeek == input.DaysOfWeek ||
                    this.DaysOfWeek != null &&
                    input.DaysOfWeek != null &&
                    this.DaysOfWeek.SequenceEqual(input.DaysOfWeek)
                ) && 
                (
                    this.Type == input.Type ||
                    this.Type.Equals(input.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Frequency.GetHashCode();
                if (this.DaysOfWeek != null)
                {
                    hashCode = (hashCode * 59) + this.DaysOfWeek.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Frequency (int) maximum
            if (this.Frequency > (int)100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Frequency, must be a value less than or equal to 100.", new [] { "Frequency" });
            }

            // Frequency (int) minimum
            if (this.Frequency < (int)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Frequency, must be a value greater than or equal to 1.", new [] { "Frequency" });
            }

            yield break;
        }
    }
}
