/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// A Workflow
    /// </summary>
    [DataContract(Name = "WorkflowResponse")]
    public partial class WorkflowResponse : IEquatable<WorkflowResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WorkflowResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowResponse" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="varVersion">varVersion.</param>
        /// <param name="displayName">Human readable name (required).</param>
        /// <param name="description">Human readable description.</param>
        /// <param name="rootTaskDefinitionId">rootTaskDefinitionId (required).</param>
        /// <param name="workflowStructure">workflowStructure.</param>
        public WorkflowResponse(ResourceId id = default(ResourceId), VersionInfo varVersion = default(VersionInfo), string displayName = default(string), string description = default(string), ResourceId rootTaskDefinitionId = default(ResourceId), WorkflowStructure workflowStructure = default(WorkflowStructure))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for WorkflowResponse and cannot be null");
            }
            this.Id = id;
            // to ensure "displayName" is required (not null)
            if (displayName == null)
            {
                throw new ArgumentNullException("displayName is a required property for WorkflowResponse and cannot be null");
            }
            this.DisplayName = displayName;
            // to ensure "rootTaskDefinitionId" is required (not null)
            if (rootTaskDefinitionId == null)
            {
                throw new ArgumentNullException("rootTaskDefinitionId is a required property for WorkflowResponse and cannot be null");
            }
            this.RootTaskDefinitionId = rootTaskDefinitionId;
            this.VarVersion = varVersion;
            this.Description = description;
            this.WorkflowStructure = workflowStructure;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public ResourceId Id { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public VersionInfo VarVersion { get; set; }

        /// <summary>
        /// Human readable name
        /// </summary>
        /// <value>Human readable name</value>
        [DataMember(Name = "displayName", IsRequired = true, EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Human readable description
        /// </summary>
        /// <value>Human readable description</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets RootTaskDefinitionId
        /// </summary>
        [DataMember(Name = "rootTaskDefinitionId", IsRequired = true, EmitDefaultValue = true)]
        public ResourceId RootTaskDefinitionId { get; set; }

        /// <summary>
        /// Gets or Sets WorkflowStructure
        /// </summary>
        [DataMember(Name = "workflowStructure", EmitDefaultValue = false)]
        public WorkflowStructure WorkflowStructure { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  RootTaskDefinitionId: ").Append(RootTaskDefinitionId).Append("\n");
            sb.Append("  WorkflowStructure: ").Append(WorkflowStructure).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WorkflowResponse);
        }

        /// <summary>
        /// Returns true if WorkflowResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of WorkflowResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkflowResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.VarVersion == input.VarVersion ||
                    (this.VarVersion != null &&
                    this.VarVersion.Equals(input.VarVersion))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.RootTaskDefinitionId == input.RootTaskDefinitionId ||
                    (this.RootTaskDefinitionId != null &&
                    this.RootTaskDefinitionId.Equals(input.RootTaskDefinitionId))
                ) && 
                (
                    this.WorkflowStructure == input.WorkflowStructure ||
                    (this.WorkflowStructure != null &&
                    this.WorkflowStructure.Equals(input.WorkflowStructure))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.VarVersion != null)
                {
                    hashCode = (hashCode * 59) + this.VarVersion.GetHashCode();
                }
                if (this.DisplayName != null)
                {
                    hashCode = (hashCode * 59) + this.DisplayName.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.RootTaskDefinitionId != null)
                {
                    hashCode = (hashCode * 59) + this.RootTaskDefinitionId.GetHashCode();
                }
                if (this.WorkflowStructure != null)
                {
                    hashCode = (hashCode * 59) + this.WorkflowStructure.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DisplayName (string) minLength
            if (this.DisplayName != null && this.DisplayName.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DisplayName, length must be greater than 1.", new [] { "DisplayName" });
            }

            yield break;
        }
    }
}
