/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Describes the structure of a Workflow as a graph of Task Definitions
    /// </summary>
    [DataContract(Name = "WorkflowStructure")]
    public partial class WorkflowStructure : IEquatable<WorkflowStructure>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkflowStructure" /> class.
        /// </summary>
        /// <param name="nodes">nodes.</param>
        /// <param name="edges">edges.</param>
        public WorkflowStructure(WorkflowStructureNodes nodes = default(WorkflowStructureNodes), WorkflowStructureEdges edges = default(WorkflowStructureEdges))
        {
            this.Nodes = nodes;
            this.Edges = edges;
        }

        /// <summary>
        /// Gets or Sets Nodes
        /// </summary>
        [DataMember(Name = "nodes", EmitDefaultValue = false)]
        public WorkflowStructureNodes Nodes { get; set; }

        /// <summary>
        /// Gets or Sets Edges
        /// </summary>
        [DataMember(Name = "edges", EmitDefaultValue = false)]
        public WorkflowStructureEdges Edges { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkflowStructure {\n");
            sb.Append("  Nodes: ").Append(Nodes).Append("\n");
            sb.Append("  Edges: ").Append(Edges).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WorkflowStructure);
        }

        /// <summary>
        /// Returns true if WorkflowStructure instances are equal
        /// </summary>
        /// <param name="input">Instance of WorkflowStructure to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkflowStructure input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Nodes == input.Nodes ||
                    (this.Nodes != null &&
                    this.Nodes.Equals(input.Nodes))
                ) && 
                (
                    this.Edges == input.Edges ||
                    (this.Edges != null &&
                    this.Edges.Equals(input.Edges))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Nodes != null)
                {
                    hashCode = (hashCode * 59) + this.Nodes.GetHashCode();
                }
                if (this.Edges != null)
                {
                    hashCode = (hashCode * 59) + this.Edges.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
