/*
 * FINBOURNE Workflow API
 *
 * Contact: info@finbourne.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Workflow.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Workflow.Sdk.Model
{
    /// <summary>
    /// Year Regularity
    /// </summary>
    [DataContract(Name = "YearRegularity")]
    public partial class YearRegularity : IEquatable<YearRegularity>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="YearRegularity" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected YearRegularity() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="YearRegularity" /> class.
        /// </summary>
        /// <param name="dates">The dates in the year (required).</param>
        /// <param name="type">The type of Date Regularity (required).</param>
        public YearRegularity(List<DayOfYear> dates = default(List<DayOfYear>), string type = default(string))
        {
            // to ensure "dates" is required (not null)
            if (dates == null)
            {
                throw new ArgumentNullException("dates is a required property for YearRegularity and cannot be null");
            }
            this.Dates = dates;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for YearRegularity and cannot be null");
            }
            this.Type = type;
        }

        /// <summary>
        /// The dates in the year
        /// </summary>
        /// <value>The dates in the year</value>
        [DataMember(Name = "dates", IsRequired = true, EmitDefaultValue = true)]
        public List<DayOfYear> Dates { get; set; }

        /// <summary>
        /// The type of Date Regularity
        /// </summary>
        /// <value>The type of Date Regularity</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class YearRegularity {\n");
            sb.Append("  Dates: ").Append(Dates).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as YearRegularity);
        }

        /// <summary>
        /// Returns true if YearRegularity instances are equal
        /// </summary>
        /// <param name="input">Instance of YearRegularity to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(YearRegularity input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Dates == input.Dates ||
                    this.Dates != null &&
                    input.Dates != null &&
                    this.Dates.SequenceEqual(input.Dates)
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Dates != null)
                {
                    hashCode = (hashCode * 59) + this.Dates.GetHashCode();
                }
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Type (string) minLength
            if (this.Type != null && this.Type.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Type, length must be greater than 1.", new [] { "Type" });
            }

            yield break;
        }
    }
}
